### ISSUE TITLE
Prioritize which questions are most important

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#180]
"In general, while there is a lot of interesting information here, there is not enough effort to prioritize it. Which questions are most important? How should tool developers allocate their resources?
"

**Comment by CaptainEmerson** [comment]
Interpretation: the questions that developers have the most difficulty answering right now.

**Comment by jssmith1** [comment]
As you suggested, our new discussion of strategic failures should help us prioritize.
