### ISSUE TITLE
Cataloging the "right question" --- Assumption Analysis

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#190]
There is a difference between cataloging the questions developers ask and cataloging the “right” questions to ask.

**Comment by CaptainEmerson** [comment]
After a chat, we have a procedure for finding wrong-questions:
* For each question, extract the assumptions
* Tie each assumption back to a previous question. 3 outcomes
    * Question was previously asked and assumption was validated. Great!
    * Question was previously asked and question was not validated. Bad!
    * Question was not asked at all. Probably bad! (But maybe we're missing data.)

Justin will do this with one strategy tree, and maybe video, and see if it yields interesting results, and at what cost.
