### ISSUE TITLE
How do information needs vary based on the vulnerability

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#325]
Is there any interesting observation about whether (and how) the needed information for analysis may vary from one vulnerability to another?

**Comment by CaptainEmerson** [comment]
Will look at categories and questions. This will be a good way to show commonalities for questions (and strategies?) across vulnerabilities.

**Comment by jssmith1** [comment]
#437 Analyzed which categories occurred during which tasks. Added to category table
