### ISSUE TITLE
this typogrpahy for section heading seems a bit...

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#358]
![snippet](https://lh3.googleusercontent.com/-EIlUIb8TlsI/WEWExJyb-JI/AAAAAAAAE6E/0U_zCBEhZok/s800/%25255BUNSET%25255D.png)

this typogrpahy for section heading seems a bit overboard. it's a heavier weight than the subsubsection it appears in, plus it's a "singleton section"

**Comment by jssmith1** [comment]
@CaptainEmerson: look better or still too much emphasis?

### Before:
![image](https://cloud.githubusercontent.com/assets/5032534/21022930/65cbb86a-bd4c-11e6-8f9e-62bd1b0be354.png)

### After:
![image](https://cloud.githubusercontent.com/assets/5032534/21022951/7e15767c-bd4c-11e6-8b31-e82a88b6c95b.png)

**Comment by CaptainEmerson** [comment]
LGTM
