### ISSUE TITLE
Validity of RQ2/3

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#421]
R2:

>To answer RQ2 (and I guess RQ3 as well) only one of the authors analyzed the transcripts for strategies (in difference to RQ 1 from the conference paper). Is there a valid reason? Are the extracted strategies and assumptions objective and complete?

**Comment by jssmith1** [comment]
Seems like two entangled issues here:
- Are the results complete? What was my stopping condition for strategy trees and assumption searches
- Are they valid? If another author analyzed/reviewed would they identify the same strategies / assumptions

**Comment by jssmith1** [comment]
Notes:
- Brittany working on verifying
- [x] compute how long it took to generate trees

**Comment by jssmith1** [comment]
@brittjay0104: Just checking in to see how this is going. Have any questions so far / run into any issues?

**Comment by drbrittjay** [comment]
@jssmith1 I had some things I needed to finish up yesterday along with meetings so I'm just getting started today. I'll update you later today but so far so good!

**Comment by drbrittjay** [comment]
@jssmith1 Update: I've gotten through Participant 7 (about to start 8 maybe, might save the rest for tomorrow). For the most part it's looking good! I have a couple of things but I know it won't take long for us to discuss/hash out. Anything I wasn't sure about I put a timestamp with it for easy reference. 
I'll let you know sometime tomorrow when I'm completely done -- maybe we can chat briefly tomorrow or Friday?

**Comment by jssmith1** [comment]
Awesome, thanks! My schedule is open tomorrow, so we can chat whenever it's convenient for you

**Comment by drbrittjay** [comment]
@jssmith1 Okie doke, I'll send a calendar invite for this afternoon. Update if the time doesn't work (I'm wide open), just not for too much earlier so I make sure I have time to finish and gather my notes :)

**Comment by jssmith1** [comment]
> I was able to identify and check off all the steps for each vulnerability.
> 
> For the following I found steps that may need to be added:
> 
> Vulnerability 2, Participant 7, approx. 14:45
> - At some point around "Determine how to use alternative securely" the participant mentions and searches notification for "seeding"
> 
> Vulnerability 3, Participant 6, approx. 24:20
> - At some point during steps for "Determine if the notification is a false positive" the participant scrolls through the list of potential problems (I believe in the notification)
> 
> Vulnerability 3, Participant 6, approx. 31:45
> - At some point during "Determine how validation method works" the participant hovered over the method checkFormat() to check the javadoc. In hindsight, this may be included in "Examine javadocs for methods the validator calls" and I just didn't realize it.

**Comment by jssmith1** [comment]
The reviewers raise a sound concern over the validity of our strategy extraction process. The initial process was rather time-consuming; we estimate ~50 hours of effort. To assess the validity and completeness of our strategy trees, without duplicating all this effort, the second author reviewed all the strategy trees while watching the corresponding videos. We added Section ??? which details this process.
