### ISSUE TITLE
Did the interviewer's prompt impact P3's tasks

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#427]
R2:

>On p12 you mention that the interviewer directed the subject to a part of the documentation he overlooked. As long as it wasn’t the last task for the subject: Did the interviewer change the behaviour of subject P3? What are the implications for the data point P3 creates? Can it be used for the evaluation?

**Comment by jssmith1** [comment]
It is possible that asking P3 to reexamine the notification text after completing T2 could have influenced that participant's subsequent tasks. In particular, by pointing out the reference links, the participant might have been more likely to follow those links in the future. However, the notification text for T3 and T4 did not include any reference links. We added this note as an aside to the relevant results section.

**Comment by jssmith1** [comment]
@CaptainEmerson: I'm not sure whether to include the previous comment in the paper, or just the response letter. The current discussion of prompting P3 comes up in one of the categories sections _Notification Text_. Thoughts?

**Comment by CaptainEmerson** [comment]
Generally, try to include something in both. If you want more details, discuss this with me in person.

**Comment by jssmith1** [comment]
Def put something in.
