### ISSUE TITLE
TSE Review Response - Round 2

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#452]
We graciously thank the reviewers and editor, again, for their helpful feedback! Please refer to our inline responses to each change request:

> Reviewer: 1 
> 
> Public Comments (these will be made available to the author) 
> I believe that authors have done a great job of addressing my comments 
> and those from the other reviewers, and I believe it is basically 
> ready for publication. I have a few minor points that I believe should 
> be fixed, but nothing that would hinder publication. I hope this is 
> published soon because I very much want to start referencing it. 
> 
> Minor writing issues: 
> 
> - col 2: "methodology, we 
> sorted 559 questions" -- unclear who "we" is here - emphasize that the 
> authors did a card sort rather than you had users do a card sort. 

Fixed.

> - Figure 1 - I had a hard time understanding this figure. Maybe the 
> problem is that the "Bug Info" window doesn't sound like a 
> vulnerability. Can you explain WHY that's a problem or better yet, use 
> an example you already explain in the body of the paper. It might also 
> be helpful to add specific labels or numbers into the figure so in the 
> body of the paper, you can refer to things like: see 2 in Fig. 1. 

We agree with the reviewer that the previous figure was not the clearest example. Figure 1 now depicts the study environment participants encountered during Task 2, the Insecure Random task. FSB's description of this vulnerability is easier to follow than the previous example. We also took the reviewer's suggestion to add labels to the figure and use those labels to refer to the figure in the text.
 
> - p. 3 line 8, typo: "measuring participants questions" --> participant's 

Fixed.

> - Task 4 code (around p. 4 line 35 - it seems you are refering to "stmt." Where is this declared? We can't see what the types are that you are talking about. 

Added the declaration:
 `Statement stmt;`

> - section 2.3.2 and 2.3.3 There is a big difference in the numbers of 
> question statements - from 421 to 559. Why the big jump? 

The paper now explains that the 559 questions include questions that were originally only identified by one of the two reviewers.

> 
> - p. 10, line 39 typo: "Whats" -> "What's" 

Fixed.

> 
> Reviewer: 3 
> 
> Public Comments (these will be made available to the author) 
> The authors tried to address all review comments, mainly by changing the text and adding details on the studied tasks, info needs strategies, and threats to validity. 
> 
> In general, I still think that the overall increment compared to the FSE paper is rather borderline (in particular impact-wise). Given the editor's recommendations, the relevance of the topic, and the improvements compared to the first version, I am leaning towards accepting this paper for publication. 
> 
> The discussion of the related work is still improvable. For instance the summary statement ``These studies give us excellent insight into the needs of developers during general programming tasks. Our work supplements theirs by taking a more focused look at how developers address security issues'' is still too general.

We replaced the summary statement with the following:
``These studies give us insight into the needs of developers during general programming tasks.
Our work examines information needs during a more specific programming task, diagnosing security vulnerabilities with static analysis.
We identified information needs unique to security, such as needs pertaining to attacks and vulnerabilities, as well as previously known information needs with novel security implications. 
Throughout [Section: Results] we have discussed how the information needs identified in previous studies overlap with the information needs we identified.''

> Also some authors also studied strategies to answer developers knowledge needs during program comprehension.

We added a paragraph in Section 5.3 that discusses studies of program comprehension strategies. With respect to R3's previous comment, we also include a summary statement that specifically relates our work to program comprehension studies.

**Comment by jssmith1** [comment]
@CaptainEmerson assigning to you in case you wanted to take a quick look at the response letter

Also, the changes to the program comprehension related work: 7b7f00ec6a3d3b4560dd76421c6ae37de007338d

**Comment by CaptainEmerson** [comment]
LGTM
